steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wi-portal-parcerias-ui:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wi-portal-parcerias-ui:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'wi-portal-parcerias-ui'
  - '--image'
  - 'gcr.io/$PROJECT_ID/wi-portal-parcerias-ui:$COMMIT_SHA'
  - '--region'
  - 'us-east1'
  - '--min-instances'
  - '1'
images:
- 'gcr.io/$PROJECT_ID/wi-portal-parcerias-ui:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY